CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar NOT NULL,
  "last_name" varchar NOT NULL,
  "password" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "age" int NOT NULL
);

CREATE TABLE "teachers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

CREATE TABLE "course_video" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "URL" varchar NOT NULL,
  "teacher_id" int NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "level_id" int NOT NULL,
  "teacher_id" int NOT NULL,
  "student_id" int NOT NULL,
  "start_date" timestamp DEFAULT 'Now()',
  "end_date" timestamp DEFAULT '01/12/2000'
);

CREATE TABLE "levels" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

CREATE TABLE "courses_categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "courses_id" int NOT NULL,
  "categories_id" int NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

ALTER TABLE "courses" ADD FOREIGN KEY ("student_id") REFERENCES "users" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("teacher_id") REFERENCES "teachers" ("id");

ALTER TABLE "course_video" ADD FOREIGN KEY ("teacher_id") REFERENCES "teachers" ("id");

ALTER TABLE "courses_categories" ADD FOREIGN KEY ("courses_id") REFERENCES "courses" ("id");

ALTER TABLE "courses_categories" ADD FOREIGN KEY ("categories_id") REFERENCES "categories" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("level_id") REFERENCES "levels" ("id");

insert into users (
	first_name,
	last_name,
	"password",
	email,
	age
) values (
	'Angelica',
	'Perez',
	'peridicoescolar',
	'angelicaperez3120@gmail.com',
	18
);

insert into users (
	first_name,
	last_name,
	"password",
	email,
	age
) values (
	'Cristopher',
	'Torres',
	'comiendocorazones',
	'cristo40tower@gmail.com',
	16
);

insert into teachers (
	"name" 
) values (
	'Jose Juan'
);

insert into teachers (
	"name" 
) values (
	'Juan Jose'
);

insert into levels  ( 
	"name"
) values (
	'inicial'
);

insert into levels (
	"name" 
) values (
	'medio'
);

insert into levels (
	"name" 
) values (
	'avanzado'
);

insert into levels (
	"name" 
) values (
	'experto'
);

insert into courses (
	"name",
	level_id,
	teacher_id,
	student_id
) values (
	'React desde CERO',
	'1',
	'2',
	'2'
);

insert into courses (
	"name",
	level_id,
	teacher_id,
	student_id
) values (
	'Creando una appMirror con React',
	'3',
	'1',
	'1'
);

insert into course_video (
	title,
	"URL",
	teacher_id 
) values ( 
	'Creando un estado - REACT',
	'https://unlinkmasdelaweb.com',
	'1'
);

insert into course_video (
	title,
	"URL",
	teacher_id
) values (
	'Desplegando en netlify el proyecto',
	'https://unlinkmasdelaweb2.com',
	'2'	
);

insert into categories (
	"name" 
) values (
	'JavaScript'
);

insert into categories (
	"name" 
) values (
	'Front-end'
);

insert into courses_categories (
	courses_id,
	categories_id 
) values (
	'1',
	'2'
);

insert into courses_categories (
	courses_id,
	categories_id 
) values (
	'2',
	'1'
);

insert into courses_categories (
	courses_id,
	categories_id 
) values (
	'1',
	'1'
);

insert into courses_categories (
	courses_id,
	categories_id 
) values (
	'2',
	'2'
);

